services:
  frontend:
    image: ${DOCKER_USERNAME}/cistl-frontend:latest
    container_name: CISTL-Frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    
  backend:
    image: ${DOCKER_USERNAME}/cistl-backend:latest
    container_name: CISTL-Backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      - backend-data:/app/data

volumes:
  backend-data: