services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: CISTL
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
