import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import { minimal_theme } from "./palette";
import ClientAppShell from "@/components/client_appshell/ClientAppShell";
import Footer from "@/components/footer/Footer";

import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "The Church in St. Louis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={minimal_theme}>
          <ClientAppShell>{children}</ClientAppShell>
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
