import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import MenuButton from "@/components/menu/MenuButton";
import FooterSocial from "@/components/footer/FooterSocial";
import { minimal_theme } from "./palette";

import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "The Church in St. Louis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={minimal_theme}>
          {children}
          <MenuButton />
          <FooterSocial />
        </MantineProvider>
      </body>
    </html>
  );
}
